---
title: "Create DEMO table as csv file"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create DEMO table from csv file}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

# Create turtle version of example files

This script creates the result and codelist for a simple DEMO table.

```{r}
knitr::read_chunk("setup.R")
```
```{r setup}
```
All files are store to the directory
```{r}
targetDir<- system.file("extdata/sample-rdf", package="rrdfqbcrnd0")
```

## RDF data cubes specified in workbook

```{r}
RDFCubeWorkbook<- system.file("extdata/sample-cfg", "RDFCubeWorkbook.xlsx", package="rrdfqbcrnd0")

dm.cube.fn<- BuildCubeFromWorkbook(RDFCubeWorkbook, "DM" )
cat("DM cube stored as ", dm.cube.fn, "\n")
targetFile<- file.path(targetDir,"DC-DM-sample.ttl")

if (file.copy( dm.cube.fn, targetFile)) {
  cat("DM cube copied to ", targetFile, "\n")
}


ae.cube.fn<- BuildCubeFromWorkbook(RDFCubeWorkbook, "AE" )
cat("AE cube stored as ", ae.cube.fn, "\n")
targetFile<- file.path(targetDir,"DC-AE-sample.ttl")
if (file.copy( ae.cube.fn, targetFile)) {
  cat("AE cube copied to ", targetFile, "\n")
}

```

## RDF data cube in csv files

```{r, eval=TRUE}
demoObsDataCsvFn<- system.file("extdata/sample-cfg", "demo.AR.csv", package="rrdfqbcrnd0")
demoObsData <- read.csv(demoObsDataCsvFn,stringsAsFactors=FALSE)

demoMetaDataCsvFn<- system.file("extdata/sample-cfg", "DEMO-Components.csv", package="rrdfqbcrnd0")
demoMetaData <- read.csv(demoMetaDataCsvFn,stringsAsFactors=FALSE)

demo.cube.fn<- BuildCubeFromDataFrames(demoMetaData, demoObsData )
cat("DEMO cube stored as ", demo.cube.fn, "\n")
targetFile<- file.path(targetDir,"DC-DEMO-sample.ttl")

if (file.copy( demo.cube.fn, targetFile)) {
   cat("DEMO cube copied to ", targetFile, "\n")
 }

```

