---
title: "Create ADSL as TTL file"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create ADSL as TTL file}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

# Create turtle version of ADSL dataset

```{r}
knitr::read_chunk("setup.R")
```
```{r setup}
```

This script creates a turtle version of the ADSL dataset.

The script uses SQLite to export the ADSL dataset, and d2rq (http://d2rq.org/) to create a turle version of the file.

```{r}
library(foreign)
fnadsl<- system.file("extdata/sample-xpt", "adsl.xpt", package="rrdfqbcrnd0")
adsl<-read.xport(fnadsl)

## Use other method for reading sas - see elsewhere

## http://cran.r-project.org/web/packages/RSQLite/RSQLite.pdf
## install.packages("RSQLite")

## Create a SQL dump - here using RSQLite - could also create the dump programically

library(RSQLite)
## create a SQLite instance and create one connection.
m <- dbDriver("SQLite")
## initialize a new database to a tempfile and copy some data.frame
## from the base package into it
tfile <- tempfile()
con <- dbConnect(m, dbname = tfile)
dbWriteTable(con, "adsl", adsl)
dbDisconnect(con)
cat("SQLite database stored as ", tfile, "\n")

dumpFn<- tempfile()
system(paste("sqlite3", tfile, ".dump >", dumpFn, sep=" "))
cat("SQLite database dump in ", dumpFn, "\n")

dumpAfterSedFn <- tempfile()

sedCmd<- paste("sed", "-e 's/TEXT/VARCHAR(1000)/g; s/\"MMSETOT\" REAL/\"MMSETOT\" REAL, PRIMARY KEY (USUBJID)/; s/\"adsl\"/adsl/g; 1,2 d; $ d; ' ", dumpFn, ">", dumpAfterSedFn, sep=" ")
system(sedCmd)
cat("SQLite database dump modified stored as ", dumpAfterSedFn, "\n")

## Check only expected changes were applied
## not run due to large output
## system(paste("diff", dumpFn, dumpAfterSedFn, sep=" "))

## The change below are for now to be applied manually!
##   change TEXT to VARCHAR(1000)
##   remove top 2 lines with PRAGMA
##   in insert statements replace "adsl"  with adsl
##   after "MMSETOT" REAL add a comma (",") and a new line with
##   PRIMARY KEY (USUBJID)
##
## see also RSQlite on dbSendQuery-methods - that can make more
## https://stat.ethz.ch/pipermail/r-sig-db/2010q1/000813.html
## d2rq documentationsee file:///opt/d2rq-0.8.1/doc/dump-rdf.html

## -b option does not work with -l

adslmapttlFn<- file.path(tempdir(), "adsl-map.ttl")
adslttlFn<- file.path(tempdir(), "adsl.ttl")

d2rqbaseURL<- "http://www.example.org/datasets/"

system(paste("/opt/d2rq-0.8.1/generate-mapping  -o ", adslmapttlFn, " -l ", dumpAfterSedFn))
system(paste("/opt/d2rq-0.8.1/dump-rdf -b ", d2rqbaseURL,  " -o ",
             adslttlFn, " -l ", dumpAfterSedFn, " ", adslmapttlFn) )
 

### This could maybe also work ..
## m <- dbDriver("SQLite")
## tfile <- tempfile()
## con <- dbConnect(m, dbname = tfile)
## s <- sprintf("create table %s(%s, primary key(%s))", "adsl",
## 		paste(names(adsl), collapse = ", "),
## 		paste(names(adsl)[c(1,2)],collapse=", ")
##              )
## dbGetQuery(con, s)

## dbWriteTable(con, "adsl", adsl,append=TRUE)
## dbDisconnect(con)
## tfile

## system(paste("sqlite3", tfile, ".dump > /tmp/xx.sql", sep=" "))
## system(paste("/opt/d2rq-0.8.1/dump-rdf -b http://localhost:3030/ -o /tmp/adsl.ttl -l /tmp/xx.sql"))

targetDir<- system.file("extdata/sample-rdf", package="rrdfqbcrnd0")
if (file.copy(adslmapttlFn, targetDir)) {
cat( "File ", adslmapttlFn, " copied to ", targetDir, "\n")
}

if (file.copy(adslttlFn, targetDir)) {
cat( "File ", adslttlFn, " copied to ", targetDir, "\n")
}

```



### Read in the file

```{r}

dataFilemap<- system.file("extdata/sample-rdf", "adsl-map.ttl", package="rrdfqbcrnd0")
dataFilemap
dataFile<- system.file("extdata/sample-rdf", "adsl.ttl", package="rrdfqbcrnd0")
dataFile

store <- new.rdf()  # Initialize
load.rdf(dataFilemap, format="TURTLE", appendTo= store)
load.rdf(dataFile, format="TURTLE", appendTo= store)
summarize.rdf(store)

rq<-"
prefix map: <#> 
prefix db: <> 
prefix vocab: <vocab/> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> 
prefix jdbc: <http://d2rq.org/terms/jdbc/> 
select * where {
?mapColumn a d2rq:PropertyBridge ;
  d2rq:column ?d2rqcolumn ;
  d2rq:datatype ?d2rqdatatype 
.
# ?mapColumn ?p ?o.
}
"

res<- data.frame(sparql.rdf(store, rq),stringsAsFactors=FALSE)
str(res)
res



s<- paste0("<", d2rqbaseURL,"ADSL/01-718-1254>")
rq<-paste0("select * where {", s, " ?p ?o . }" )
print(rq)

res<- data.frame(sparql.rdf(store, rq),stringsAsFactors=FALSE)
str(res)
res$pclean<- gsub(paste0(d2rqbaseURL,"vocab/ADSL_"), "", res$p)
knitr::kable(res[,c("p","o")])


```
