---
title: "Usage of cube DEMO"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Usage of cube DEMO}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

# Introduction

This is not a good example yet.
TODO(mja): fix it.

# Create DEMO sample table from CSV file

This script creates the result and codelist for a simple DEMO table.

```{r, eval=TRUE}
library(rrdfqbcrnd0)

dataCubeSpec<- system.file("extdata/CUBE-standards-rdf", "cube.ttl", package="rrdfqbcrnd0")

dataCubeFile<- system.file("extdata/sample-rdf", "DC-DEMO-sample.TTL", package="rrdfqbcrnd0")

store <- new.rdf()  # Initialize

cat("Loading cube specfication from ", dataCubeSpec, "\n")
load.rdf(dataCubeSpec, format="TURTLE", appendTo= store)

cat("Loading cube from ", dataCubeFile, "\n")
load.rdf(dataCubeFile, format="TURTLE", appendTo= store)

summarize.rdf(store)

```


## This works do not change

```{r, eval=TRUE}

rq<-  paste( forsparqlprefix,
'
select *
where { 
?s a qb:Observation ; 
?p ?o ;
.
[] qb:dimension ?p .
values (?s) {
(ds:obs114)
}
}
# limit 30
',
"\n"                               
)

cube.observations<- sparql.rdf(store, rq)
knitr::kable(cube.observations)


```

### Check the statistics

```{r, eval=TRUE}

stmtSQL<- GetSQLFromCube(store) 
cat(stmtSQL$summStatSQL) 

```
