library (rrdf)
# library (car)
# library (Hmisc)

source("BuildCube-functions-0-5-0.R")

require(foreign)

xptdirectory= "."
fnadae=paste(xptdirectory,"/", "adae", ".xpt",sep="")
# download.file("http://phuse-scripts.googlecode.com/svn/trunk/scriptathon2014/data/adae.xpt", fnadae)
adae=read.xport(fnadae)

require(sqldf)
aesummay.e<- sqldf("select TRTA, SAFFL, '_ALL_' as AESOC, '_ALL_' as AEDECOD, 'count' as procedure, 'quantity' as factor, count(*) as measure from adae group by TRTA", stringsAsFactors=FALSE )
aesoc.e<- sqldf("select TRTA, SAFFL, AESOC, '_ALL_' as AEDECOD, 'count' as procedure, 'quantity' as factor, count(*) as measure from adae group by TRTA, SAFFL, AESOC", stringsAsFactors=FALSE )
aesocpt.e<- sqldf("select TRTA, SAFFL, AESOC, AEDECOD, 'count' as procedure, 'quantity' as factor, count(*) as measure from adae group by TRTA, SAFFL, AESOC, AEDECOD", stringsAsFactors=FALSE )

aesummay.n<- sqldf("select TRTA, SAFFL, '_ALL_' as AESOC, '_ALL_' as AEDECOD, 'countdistinct' as procedure, 'USUBJID' as factor, count(distinct USUBJID) as measure from adae group by TRTA", stringsAsFactors=FALSE )
aesoc.n<- sqldf("select TRTA, SAFFL, AESOC, '_ALL_' as AEDECOD, 'countdistinct' as procedure, 'USUBJID' as factor, count(distinct USUBJID) as measure from adae group by TRTA, SAFFL, AESOC", stringsAsFactors=FALSE )
aesocpt.n<- sqldf("select TRTA, SAFFL, AESOC, AEDECOD, 'countdistinct' as procedure, 'USUBJID' as factor, count(distinct USUBJID) as measure from adae group by TRTA, SAFFL, AESOC, AEDECOD", stringsAsFactors=FALSE )

aetable<- rbind(aesummay.e, aesummay.n, aesoc.e, aesoc.n, aesocpt.e, aesocpt.n )
aetable$unit<- "_NULL_"
aetable$denominator<- "_NULL_"
names(aetable)<- tolower(names(aetable))

write.csv(aetable, file="ae.AR.csv",row.names=FALSE)

recode.aesoc.list<- sqldf("select distinct AESOC from adae", stringsAsFactors=FALSE)
names(recode.aesoc.list)<- tolower(names(recode.aesoc.list))
recode.aesoc.list<- rbind(recode.aesoc.list, data.frame(aesoc="_ALL_"))
for (i in 1:nrow(recode.aesoc.list)) { recode.aesoc.list[i,"recodeto"]<- encodetouri(as.character(recode.aesoc.list[i,1])) }
write.csv(recode.aesoc.list, file="ae.aesoc.AR.csv",row.names=FALSE)

recode.aedecod.list<- sqldf("select distinct AEDECOD from adae", stringsAsFactors=FALSE )
names(recode.aedecod.list)<- tolower(names(recode.aedecod.list))
recode.aedecod.list<- rbind(recode.aedecod.list, data.frame(aedecod="_ALL_"))
for (i in 1:nrow(recode.aedecod.list)) { recode.aedecod.list[i,"recodeto"]<- encodetouri(as.character(recode.aedecod.list[i,1])) }
write.csv(recode.aedecod.list, file="ae.aedecod.AR.csv",row.names=FALSE)
