---
title: AE table from CSV file"
author: "PhuseSubTeamAnalysisResults@example.org"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{AE table from CSV file}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---


## Prelimnaries
The present version uses Apache Fuseki to access CDISC in RDF from rdf.cdisc.org.


## Code


```{r}

library (rrdf)

library(rrdfqbcrnd0)


#------------  Declarations    ------------------------------------------------
endpoint<- "http://localhost:3030/cdisc/query"

cubeVersion <- "0-5-2"  # For pav:Version (dot, notdash) and output file name
# dataDir <- "C:/_Sandbox/r/semanticWeb/data/"  # Input and output files
dataDir <- "./"  # Input and output files
prefixSourceFile  <- paste0(dataDir,"CubePrefixes.csv")    

AEdsdName <- "dsd-ae"
AEskeletonSourceFile <- paste0(dataDir,"skeletonSource-AE.csv") 

# Cube Observation data       
AEobsFileName <-"ae.AR.csv" # Source of obs. Filename needed for cube metadata
AEobsFile     <- paste0(dataDir,AEobsFileName)  # Full path to obs. file


# These codelist could also go in a RDF codelists instead of CSV files
AE.recode.aesoc.list<- read.csv(file="ae.aesoc.AR.csv")
aesoc.list= list();
for (i in 1:nrow(AE.recode.aesoc.list)) {
  aesoc.list[[ as.character(AE.recode.aesoc.list[i,1]) ]]=
       encodetouri( paste0("aesoc-",as.character(AE.recode.aesoc.list[i,2])) )
}

AE.recode.aedecod.list<- read.csv(file="ae.aedecod.AR.csv")
aedecod.list= list();
for (i in 1:nrow(AE.recode.aedecod.list)) {
  aedecod.list[[ as.character(AE.recode.aedecod.list[i,1]) ]]= encodetouri( paste0("aedecod-",as.character(AE.recode.aedecod.list[i,2])) )
}



AE.recode.list= list(
    "saffl"=list('Y'='saffl-Y',
                        'N'='saffl-N',
                        '_ALL_'='saffl-_ALL_'),
    "trta"=list('Placebo'='trta-Placebo',
                         'Xanomeline High Dose'='trta-Xanomeline_High_Dose',
                         'Xanomeline Low Dose'='trta-Xanomeline_Low_Dose',
                         '_ALL_'='trta-_ALL_' ),
    "aesoc"=aesoc.list,
    "aedecod"=aedecod.list,
    "factor"=list('quantity'='factor-QUANTITY',
                         'proportion'='factor-PROPORTION', 
                         'AGE'='factor-AGE',
      'USUBJID'='factor-USUBJID'
      ),
    "procedure"= list('count'='procedure-COUNT',
      'countdistinct'='procedure-COUNTDISTINCT',
                            'percent'='procedure-PERCENT', 
                            'mean'='procedure-MEAN', 
                            'stdev'='procedure-STDDEV', 
                            'min'='procedure-MIN', 
                            'median'='procedure-MEDIAN', 
                            'max'='procedure-MAX' )
  )

  procedure2format= list("count"="int",
                         "countdistinct"="int",
                            'percent'='double', 
                            'mean'='double', 
                            'stdev'='double', 
                            'min'='double', 
                            'median'='double', 
                            'max'='double'                         

     );



AEdataCubeFileName  <- paste0("DC-AE-R-V-",cubeVersion,".TTL")   
AEdataCubeFile      <- paste0(dataDir,AEdataCubeFileName) # Full path to cube
  
storeAE = new.rdf(ontology=FALSE)  # Initialize

prefixSource = read.csv(prefixSourceFile) 

AEprefixlist= qb.def.prefixlist(storeAE, prefixSource)

AEskeletonSource = read.csv(AEskeletonSourceFile) 

AEobsData = read.csv(AEobsFile) 
names(AEobsData)= tolower(names(AEobsData))


qb.buildSkeleton(storeAE, AEprefixlist, AEobsData, AEskeletonSource)

qb.buildDSD(storeAE, AEprefixlist, AEobsData, AEskeletonSource,
            dsdURIwoprefix="dataset-ae",
            dsdName=AEdsdName,
            extra=list(description="Cube with XX dimensions and 1 measure (measure)",
comment="Adverse event sample table ",
label="Adverse events results data set.",
distribution=AEdataCubeFileName,
obsfilename=AEobsFileName,
title="Adverse Event Analysis Results"
 )            )

qb.buildObservations( store=storeAE, prefixlist=AEprefixlist, obsData=AEobsData, skeletonSource=AEskeletonSource, dsdURIwoprefix="dataset-ae", recode.list=AE.recode.list, procedure2format=procedure2format )

##########
# Output #
###############################################################################
AEoutcube = save.rdf(storeAE, filename=AEdataCubeFile, format="TURTLE")

```


Now look at the cube. Note: by specifying prefix the output contains is shown using the prefixes.
Note for future: This may be a disadvantage if the value of the prefix, say ds, changes.

```{r, echo=FALSE, results='asis'}

checkAE = new.rdf(ontology=FALSE)  # Initialize
load.rdf("DC-AE-R-V-0-5-2.TTL", format="TURTLE", appendTo= checkAE)
summarize.rdf(checkAE)


## ------------------------------------------------------------------------

myprefixes= list(
 "rdf"= "http://www.w3.org/1999/02/22-rdf-syntax-ns#" ,
 "skos"="http://www.w3.org/2004/02/skos/core#" ,
 "prov"="http://www.w3.org/ns/prov#" ,
 "rdfs"="http://www.w3.org/2000/01/rdf-schema#" ,
 "dcat"="http://www.w3.org/ns/dcat#" ,
 "owl"= "http://www.w3.org/2002/07/owl#" ,
 "xsd"= "http://www.w3.org/2001/XMLSchema#" ,
 "qb"=  "http://purl.org/linked-data/cube#" ,
 "pav"= "http://purl.org/pav" ,
 "dct"= "http://purl.org/dc/terms/" ,
 "mms"= "http://rdf.cdisc.org/mms#" ,
 "cts"= "http://rdf.cdisc.org/ct/schema#" ,
 "dccs"="http://www.example.org/dc/demog/dccs/" ,
 "code"="http://www.example.org/dc/code/" ,
 "ds"=  "http://www.example.org/dc/demog/dataset/" ,
 "prop"="http://www.example.org/dc/demog/prop/",
 "valid"="http://www.example.org/dc/demog/valid/"
)  ;


forsparqlprefix= paste("prefix", paste(names(myprefixes),":",sep=""), paste("<",myprefixes,">",sep=""),sep=" ",collapse=" ")

cube.observations1= sparql.rdf(checkAE,
   paste( forsparqlprefix,
     "select * where {?s ?p ?o .} limit 10"
     )
   );
knitr::kable(head(cube.observations1, 10))


cube.observations2= sparql.rdf(checkAE,
   paste( forsparqlprefix,
     "select * where { ?s a qb:Observation ; ?p ?o .}"
     )
   );
knitr::kable(head(cube.observations2, 10))
```
