---
title: "Execute SPARQL integrity constraints on a data cube"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{Execute SPARQL integrity constraints on a data cube}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## Checking two existing cube

```{r, results='asis', eval=TRUE}
library(rrdf)
library(rrdfqb)
library(rrdfqbcrnd0)

cube.vocabulary.ttl <- file.path(system.file("extdata/cube-vocabulary-rdf", "cube.ttl", package="rrdfqb") )
cubevoc<- load.rdf( cube.vocabulary.ttl, format="TURTLE" )

qbfile1<- system.file("extdata/sample-rdf", "example.ttl", package="rrdfqb")
cube1<- load.rdf( qbfile1, format="TURTLE")

cubeData1<- combine.rdf( cube1, cubevoc)
forsparqlprefix<- GetForSparqlPrefix()

icres1<- RunQbIC( cubeData1, forsparqlprefix )
knitr::kable(icres1)
```

The file example-fails-IC14.ttl is example.ttl with a few triples added to make the cube non conformant with the intregity constaints.

```{r, results='asis', eval=TRUE}
qbfile2<- system.file("extdata/sample-rdf", "example-fails-IC14.ttl", package="rrdfqb")
cube2<- load.rdf( qbfile2, format="TURTLE")

cube.vocabulary.ttl <- file.path(system.file("extdata/cube-vocabulary-rdf", "cube.ttl", package="rrdfqb") )
cubevoc<- load.rdf( cube.vocabulary.ttl, format="TURTLE" )

cubeData2<- combine.rdf( cube2, cubevoc)

icres2<- RunQbIC( cubeData2, forsparqlprefix, doForIC=c("ic-14") )
knitr::kable(icres2)
```

