---
title: "SPARQL update example"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SPARQL update example}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---


### How to run from command prompt when developing

Start in the package root directory

Devtools should reply reply `Loading rrdfancillary`.

The knit command should generate .md file in the present work directory - the package root directory


```{r, eval=FALSE}
library(devtools)
devtools::document()
devtools::load_all("..")
devtools::install()
library(knitr)
knit("vignettes/do-update.Rmd")
library(rrdfancillary)
```

```{r, eval=TRUE}
library(rrdf)
library(rrdfancillary)
store <- new.rdf()
add.data.triple(store,
                subject="http://example.org/Subject",
                predicate="http://example.org/Predicate",
                data="Value")
cat(asString.rdf(store))

SPARQLinsert<- '
PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA
{ 
  <http://example/book1> dc:title "A new book" ;
                         dc:creator "A.N.Other" .
}
'

update.rdf( store, SPARQLinsert )

cat(asString.rdf(store))

```
