---
title: "Create DM table as csv file"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create DM table as csv file}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Create DM sample table as CSV file and other files

This script creates the result and codelist for a simple DM table.


```{r, results='asis', eval=FALSE}

library(devtools)

library(foreign)
library(sqldf)

xptdirectory<- tempdir()

fnadsl<- paste(xptdirectory,"/", "adsl", ".xpt",sep="")

download.file("http://phuse-scripts.googlecode.com/svn/trunk/scriptathon2014/data/adsl.xpt", fnadsl)

adsl<- read.xport(fnadsl)
adsl$TRT01A<- as.character(adsl$TRT01A)
adsl$RACE<- as.character(adsl$RACE)
adsl$SAFFL<- as.character(adsl$SAFFL)
adsl$SEX<- as.character(adsl$SEX)

## SASxport package maps characters and dates etc into more R like data type
## install.packages("SASxport")
## library(SASxport)
## adsl<- as.data.frame(read.xport(fnadsl,as.is=TRUE))
## str(adsl)

library(rrdfqbcrnd0)
stmtSQL<- GetSQLFromCube(checkCube)

# str(stmtSQL)
# cat(stmtSQL$summStatSQL)
adsl.summ.stat.res<- sqldf( stmtSQL$summStatSQL)
cat(stmtSQL$summStatSQL)
# adsl.summ.stat$unit<- "_NULL_"
names(adsl.summ.stat.res)<- tolower(gsub("(a|b)\\.","", names(adsl.summ.stat.res)))
# str(adsl.summ.stat.res)
# names(adsl.summ.stat.res)
# names(stmtSQL$qbframe)

# apply(stmtSQL$qbframe,c(1,2),function(x) {paste0("'",x,"'")})

```

```{r, results='asis', eval=FALSE}

res.text<- stmtSQL$summStatSQL

cr.text<-   paste0("create table qbframe ", "(", paste(names(stmtSQL$qbframe), "TEXT", collapse=", "), ")",";")

in.text<-   paste0(
  paste(
  paste0("insert into qbframe ", "(", paste0(names(stmtSQL$qbframe),collapse=","), ")\n" ),
  "values\n",
  paste0( "(", apply(stmtSQL$qbframe,1,function(x) {paste0('"',x,'"', collapse=",")}), ")",  collapse=",\n"),
  collapse="\n"
  ),";\n")

se.text<- "select * from qbframe;"

cat(res.text,file="res.txt")
cat(cr.text,file="cr.txt")
cat(in.text,file="in.txt")
cat(se.text,file="se.txt")

```

```{r, results='asis', eval=FALSE}
res.text<- "
SELECT a.TRT01A, '_ALL_' as RACE, a.SEX, a.SAFFL, 'count' as procedure, 'quantity' as factor, '_ALL_' as denominator, '_NULL_' as unit, count(*) as measure from  adsl  as a   group by  a.TRT01A, a.SEX, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'mean' as procedure, 'WEIGHTBL' as factor, '_NULL_' as denominator, 'KG' as unit, avg(WEIGHTBL) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'max' as procedure, 'WEIGHTBL' as factor, '_NULL_' as denominator, 'KG' as unit, max(WEIGHTBL) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'max' as procedure, 'AGE' as factor, '_NULL_' as denominator, 'YEARS' as unit, max(AGE) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'median' as procedure, 'WEIGHTBL' as factor, '_NULL_' as denominator, 'KG' as unit, median(WEIGHTBL) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, a.RACE, '_ALL_' as SEX, a.SAFFL, 'count' as procedure, 'quantity' as factor, '_ALL_' as denominator, '_NULL_' as unit, count(*) as measure from  adsl  as a   group by  a.TRT01A, a.RACE, a.SAFFL
UNION
SELECT a.TRT01A, b.RACE, '_ALL_' as SEX, a.SAFFL, 'percent' as procedure, 'proportion' as factor, 'RACE' as denominator, '_NULL_' as unit, 100*avg(a.RACE=b.RACE) as measure from  adsl  as a , (select distinct RACE from adsl) as b group by  a.TRT01A, b.RACE, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'stdev' as procedure, 'AGE' as factor, '_NULL_' as denominator, 'YEARS' as unit, stdev(AGE) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'min' as procedure, 'AGE' as factor, '_NULL_' as denominator, 'YEARS' as unit, min(AGE) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, b.SEX, a.SAFFL, 'percent' as procedure, 'proportion' as factor, 'SEX' as denominator, '_NULL_' as unit, 100*avg(a.SEX=b.SEX) as measure from  adsl  as a , (select distinct SEX from adsl) as b group by  a.TRT01A, b.SEX, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'min' as procedure, 'WEIGHTBL' as factor, '_NULL_' as denominator, 'KG' as unit, min(WEIGHTBL) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT '_ALL_' as TRT01A, a.RACE, '_ALL_' as SEX, a.SAFFL, 'count' as procedure, 'quantity' as factor, '_ALL_' as denominator, '_NULL_' as unit, count(*) as measure from  adsl  as a   group by  a.RACE, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'mean' as procedure, 'AGE' as factor, '_NULL_' as denominator, 'YEARS' as unit, avg(AGE) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT '_ALL_' as TRT01A, '_ALL_' as RACE, a.SEX, a.SAFFL, 'count' as procedure, 'quantity' as factor, '_ALL_' as denominator, '_NULL_' as unit, count(*) as measure from  adsl  as a   group by  a.SEX, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'median' as procedure, 'AGE' as factor, '_NULL_' as denominator, 'YEARS' as unit, median(AGE) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'count' as procedure, 'quantity' as factor, '_ALL_' as denominator, '_NULL_' as unit, count(*) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
UNION
SELECT a.TRT01A, '_ALL_' as RACE, '_ALL_' as SEX, a.SAFFL, 'stdev' as procedure, 'WEIGHTBL' as factor, '_NULL_' as denominator, 'KG' as unit, stdev(WEIGHTBL) as measure from  adsl  as a   group by  a.TRT01A, a.SAFFL
"


cr.text<- '
create table qbframe (trt01a TEXT, race TEXT, factor TEXT, procedure TEXT, sex TEXT, saffl TEXT, unit TEXT, denominator TEXT);
'

in.text<- '
insert into qbframe (trt01a,race,factor,procedure,sex,saffl,unit,denominator)
 values
("Xanomeline High Dose","AMERICAN INDIAN OR ALASKA NATIVE","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Xanomeline Low Dose","AMERICAN INDIAN OR ALASKA NATIVE","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Xanomeline Low Dose","BLACK OR AFRICAN AMERICAN","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Placebo","_ALL_","quantity","count","F","Y","_NULL_","_ALL_"),
("_ALL_","WHITE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","_ALL_","AGE","min","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","_ALL_","AGE","stdev","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline Low Dose","_ALL_","proportion","percent","M","Y","_NULL_","SEX"),
("Placebo","_ALL_","AGE","stdev","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","WHITE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","WHITE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline High Dose","_ALL_","AGE","max","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","AMERICAN INDIAN OR ALASKA NATIVE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Placebo","BLACK OR AFRICAN AMERICAN","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Placebo","_ALL_","AGE","max","_ALL_","Y","YEARS","_NULL_"),
("Placebo","AMERICAN INDIAN OR ALASKA NATIVE","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Placebo","BLACK OR AFRICAN AMERICAN","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Xanomeline Low Dose","_ALL_","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Placebo","_ALL_","quantity","count","M","Y","_NULL_","_ALL_"),
("Placebo","_ALL_","proportion","percent","F","Y","_NULL_","SEX"),
("Xanomeline High Dose","_ALL_","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","_ALL_","quantity","count","M","Y","_NULL_","_ALL_"),
("Xanomeline High Dose","_ALL_","proportion","percent","F","Y","_NULL_","SEX"),
("Xanomeline Low Dose","_ALL_","quantity","count","F","Y","_NULL_","_ALL_"),
("Placebo","_ALL_","AGE","mean","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","_ALL_","AGE","median","_ALL_","Y","YEARS","_NULL_"),
("Placebo","_ALL_","AGE","min","_ALL_","Y","YEARS","_NULL_"),
("_ALL_","BLACK OR AFRICAN AMERICAN","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Placebo","_ALL_","AGE","median","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline Low Dose","_ALL_","AGE","stdev","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline Low Dose","AMERICAN INDIAN OR ALASKA NATIVE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","BLACK OR AFRICAN AMERICAN","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","_ALL_","AGE","max","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","BLACK OR AFRICAN AMERICAN","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Xanomeline High Dose","WHITE","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Xanomeline Low Dose","WHITE","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("_ALL_","_ALL_","quantity","count","M","Y","_NULL_","_ALL_"),
("Xanomeline High Dose","_ALL_","quantity","count","M","Y","_NULL_","_ALL_"),
("_ALL_","_ALL_","quantity","count","F","Y","_NULL_","_ALL_"),
("Xanomeline High Dose","_ALL_","quantity","count","F","Y","_NULL_","_ALL_"),
("Placebo","_ALL_","proportion","percent","M","Y","_NULL_","SEX"),
("Xanomeline Low Dose","_ALL_","proportion","percent","F","Y","_NULL_","SEX"),
("Xanomeline Low Dose","_ALL_","AGE","mean","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","_ALL_","proportion","percent","M","Y","_NULL_","SEX"),
("Placebo","AMERICAN INDIAN OR ALASKA NATIVE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline High Dose","_ALL_","AGE","mean","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","BLACK OR AFRICAN AMERICAN","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Placebo","WHITE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","_ALL_","AGE","median","_ALL_","Y","YEARS","_NULL_"),
("Xanomeline High Dose","_ALL_","AGE","min","_ALL_","Y","YEARS","_NULL_"),
("_ALL_","AMERICAN INDIAN OR ALASKA NATIVE","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Placebo","WHITE","proportion","percent","_ALL_","Y","_NULL_","RACE"),
("Placebo","_ALL_","quantity","count","_ALL_","Y","_NULL_","_ALL_"),
("Xanomeline Low Dose","_ALL_","WEIGHTBL","min","_ALL_","Y","KG","_NULL_"),
("Xanomeline High Dose","_ALL_","WEIGHTBL","stdev","_ALL_","Y","KG","_NULL_"),
("Placebo","_ALL_","WEIGHTBL","stdev","_ALL_","Y","KG","_NULL_"),
("Xanomeline High Dose","_ALL_","WEIGHTBL","max","_ALL_","Y","KG","_NULL_"),
("Placebo","_ALL_","WEIGHTBL","max","_ALL_","Y","KG","_NULL_"),
("Placebo","_ALL_","WEIGHTBL","mean","_ALL_","Y","KG","_NULL_"),
("Xanomeline High Dose","_ALL_","WEIGHTBL","median","_ALL_","Y","KG","_NULL_"),
("Placebo","_ALL_","WEIGHTBL","min","_ALL_","Y","KG","_NULL_"),
("Placebo","_ALL_","WEIGHTBL","median","_ALL_","Y","KG","_NULL_"),
("Xanomeline Low Dose","_ALL_","WEIGHTBL","stdev","_ALL_","Y","KG","_NULL_"),
("Xanomeline Low Dose","_ALL_","WEIGHTBL","max","_ALL_","Y","KG","_NULL_"),
("Xanomeline Low Dose","_ALL_","WEIGHTBL","mean","_ALL_","Y","KG","_NULL_"),
("Xanomeline High Dose","_ALL_","WEIGHTBL","mean","_ALL_","Y","KG","_NULL_"),
("Xanomeline Low Dose","_ALL_","WEIGHTBL","median","_ALL_","Y","KG","_NULL_"),
("Xanomeline High Dose","_ALL_","WEIGHTBL","min","_ALL_","Y","KG","_NULL_")
;
'
se.text<-'
select * from qbframe;
'

```

```{r, results='asis', eval=FALSE}

adsl.summ.stat.res<- sqldf( res.text )
# adsl.summ.stat$unit<- "_NULL_"
names(adsl.summ.stat.res)<- tolower(gsub("(a|b)\\.","", names(adsl.summ.stat.res)))

rm(qbframe)
sqldf()
sqldf(cr.text )
sqldf(in.text  )
qbframe<- sqldf(se.text)
sqldf()
# str(qbframe)

```

```{r, results='asis', eval=FALSE}

adsl.summ.stat<- merge(qbframe,adsl.summ.stat.res,by=names(qbframe),all=TRUE)
# adsl.summ.stat<- merge(stmtSQL$qbframe,adsl.summ.stat.res,all=TRUE)
adsl.summ.stat$measure[ is.na(adsl.summ.stat$measure) & adsl.summ.stat$procedure=="count" ]<- 0
adsl.summ.stat

dmtableFile<- system.file("extdata/sample-cfg", "dm.AR.csv", package="rrdfqbcrnd0")
write.csv(adsl.summ.stat, file=dmtableFile, row.names=FALSE)


```


```{r, results='asis', eval=FALSE}


colorder<- c( "saffl", "trt01a", "race", "sex", "procedure", "factor", "denominator", "unit", "measure")
dmtableprevFile<- system.file("extdata/sample-cfg", "dm-prev.AR.csv", package="rrdfqbcrnd0")
dmtable<- read.csv(dmtableprevFile,stringsAsFactors=FALSE)
names(dmtable)<-tolower(names(dmtable))
## str(dmtable)
Sort <- function(DF) DF[do.call(order, DF),]
fromCSV.for.all.equal<- Sort(dmtable[,colorder])
## str(adsl.summ.stat)
xadsl.summ.stat<- adsl.summ.stat[,colorder]
# fromSQL.for.all.equal<- Sort(xadsl.summ.stat[ , intersect(names(fromCSV.for.all.equal),names(xadsl.summ.stat)) ])
fromSQL.for.all.equal<- Sort(xadsl.summ.stat[ , intersect(names(fromCSV.for.all.equal),names(xadsl.summ.stat)) ])
## str(fromSQL.for.all.equal)
## str(fromCSV.for.all.equal)
all.equal(fromCSV.for.all.equal, fromSQL.for.all.equal, check.attributes = FALSE)
## fromSQL.for.all.equal
## fromCSV.for.all.equal
compare<-merge(fromSQL.for.all.equal, fromCSV.for.all.equal,by=setdiff(colorder,"measure"),all=TRUE)
## not clever
compare$isequal<- abs(compare$measure.x - compare$measure.y ) < 1e-6
compare

```
